<?php
/**
 * @author Gustavo Ulyssea - gustavo.ulyssea@gmail.com
 * @copyright Copyright (c) 2020-2022 GumNet (https://gum.net.br)
 * @package GumNet AME
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY GUM Net (https://gum.net.br). AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$assetRepo = $objectManager->get('Magento\Framework\View\Asset\Repository');
$ame_logo = $assetRepo->getUrl("GumNet_AME::images/ame-logo.png");
/** @var \Magento\Checkout\Model\Session $checkoutSession */
$checkoutSession = $objectManager->get('Magento\Checkout\Model\Session');
$quote = $checkoutSession->getQuote();
$grandTotal = $checkoutSession->getQuote()->getTotals()['grand_total']->getValue();
if (array_key_exists('discount', $quote->getTotals())) {
    $grandTotal = $checkoutSession->getQuote()->getGrandTotal() - $quote->getTotals()['discount']->getValue();
}

$api = $objectManager->get('GumNet\AME\Helper\API');
/** @var \GumNet\AME\Helper\API $cashbackPercent */
$cashbackPercent = $api->getCashbackPercent();
$cashbackValue = $grandTotal * $cashbackPercent * 0.01;

$cashback_text = "";

$cashback_text = "&nbsp;&nbsp;Receba R$"
    . number_format($cashbackValue, "2", ",", ".")
    . " de volta com a AME Digital";
?>
<div id="ameLogoHtml" style="display: none;"><?php echo $ame_logo; ?></div>
<div id="cashbackTxtHtml" style="display: none;"><?php echo $cashback_text; ?></div>
