<?php
/**
 * @author Gustavo Ulyssea - gustavo.ulyssea@gmail.com
 * @copyright Copyright (c) 2020-2022 GumNet (https://gum.net.br)
 * @package GumNet AME
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY GUM Net (https://gum.net.br). AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

use GumNet\AME\Block\QrCode;

/** @var $block QrCode */
$ame_logo = $block->getLogoUrl();

if ($block->getPaymentMethod() === "ame" && $block->getOrder()) {
    $total_discount = 0;
    $items = $block->getOrder()->getAllItems();
    foreach ($items as $item) {
        $total_discount += $item->getDiscountAmount();
    }
    ?>
    <div id='success_ame_external'>
        <center>
        <div id='success_ame_internal'>
            &nbsp;<br>
            <div id="success_ame_value_txt">
                <img alt="AME Logo" src="<?=$block->escapeHtml($ame_logo)?>" width="150"><br><br>
                Valor da compra:
            </div>
            <div id="success_ame_value">
                <?=$block->escapeHtml("R$" . number_format($block->getPrice(), 2, ",", ".")) ?>
            </div>
            <br>
            <?php if ($block->getCashbackValue()) { ?>
            <div id="success_ame_cashback_txt">Receba de volta
                <div id="success_ame_cashback_value">
                    <?=$block->escapeHtml(number_format($block->getCashbackValue(), 2, ",", "."))?>
                </div> em até 30 dias.</div><br>
                    <?php } ?>
            <div id="success_ame_facil">Pagar com a AME é fácil e rápido!</div>
            <img id="success_ame_qrcode" alt="QR Code" src='<?=$block->escapeHtml($block->getQrCodeLink())?>'/>
            <div id="success_ame_info">1. Abra o aplicativo Ame Digital. Se você ainda não tem, <br>baixe no
                <img src="<?=$block->escapeHtml($block->getViewFileUrl('GumNet_AME::images/google-logo.svg'))?>"
                     alt='Google Play' height="16">
                ou na
                <img src="<?=$block->escapeHtml($block->getViewFileUrl('GumNet_AME::images/apple-logo.svg'))?>"
                     alt='App Store' height="16"><br>
                2. Clique em pagar
                <img src="<?=$block->escapeHtml($block->getViewFileUrl('GumNet_AME::images/ame-small-logo.svg'))?>"
                     alt='AME Logo'>
                e aponte para o QR Code.<br>
                3. Pronto, agora é só finalizar o pagamento com Ame.<br>
                <br>
            </div>
            <br>
            <br>
            <br>
        </div>
        </center>
        <script>
            if(window.innerWidth<=500){
                window.location = "<?=$block->escapeHtml($block->getDeepLink());?>";
            }
        </script>
    </div>
<script>
requirejs(['jquery'], function($){
    var updatePaymentLoop = setInterval(updatePaymentConfirmation,3000);

    function paymentConfirmed(){
        var msgPagamentoConfirmado = "<br><br><br>Recebemos seu pagamento.<br><br>" +
            "Muito obrigado pela compra!<br><br>Enviaremos atualizações para seu email cadastrado.<br><br><br>";
        $('#success_ame_facil').remove();
        $('#success_ame_qrcode').remove();
        $('#success_ame_info').remove();
        $('#success_ame_cashback_txt').html($('#success_ame_cashback_txt').html() + msgPagamentoConfirmado);
    }
    function updatePaymentConfirmation()
    {
        $.ajax({
            url: "/m2amecallbackendpoint/paymentconfirmation/index/id/" +
                "<?=$block->escapeHtml($block->getOrder()->getEntityId())?>",
            context: document.body
        }).done(function (resposta) {
            console.log(resposta);
            if (resposta === "1") {
                paymentConfirmed();
                clearInterval(updatePaymentLoop);
            }
        });
    }
});

</script>
    <?php }
