<?php
/**
 * @author Gustavo Ulyssea - gustavo.ulyssea@gmail.com
 * @copyright Copyright (c) 2020-2021 GumNet (https://gum.net.br)
 * @package GumNet AME
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY GUM Net (https://gum.net.br). AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_request = $objectManager->get('\Magento\Framework\App\Request\Http');
$_apiAME = $objectManager->get('\GumNet\AME\Helper\API');
$_formKey = $objectManager->get('\Magento\Framework\Data\Form\FormKey');
$_order = $objectManager->get('\Magento\Sales\Api\OrderRepositoryInterface');
$_dbAME = $objectManager->get('\GumNet\AME\Helper\DbAME');
$_invoiceService = $objectManager->get('\Magento\Sales\Model\Service\InvoiceService');

$_transactionFactory = $objectManager->get('\Magento\Framework\DB\TransactionFactory');

$id = $_request->getParam('id');


$order = $_order->get($id);
$increment_id = $order->getIncrementId();

$ame_order_id = $_dbAME->getAmeIdByIncrementId($increment_id);
$ame_transaction_id = $_dbAME->getTransactionIdByOrderId($ame_order_id);
$order_amount = $_dbAME->getTransactionAmount($ame_transaction_id);

$admin_url = $this->helper('Magento\Backend\Helper\Data')->getHomePageUrl();

$formkey = $_formKey->getFormKey();


$capture = $_apiAME->captureOrder($ame_order_id);

if($capture) {
    $invoice = $_invoiceService->prepareInvoice($order);
    $invoice->setRequestedCaptureCase(\Magento\Sales\Model\Order\Invoice::CAPTURE_ONLINE);
    $invoice->register();
    $transaction = $_transactionFactory->create()
        ->addObject($invoice)
        ->addObject($invoice->getOrder());
    $transaction->save();
    $order->setState('processing')->setStatus('processing');
    $order->save();
}

if(!$capture){
    $mensagem = "Aconteceu um erro capturando seu pedido.";
}
else{
    $mensagem = "Pedido capturado com sucesso.";
}

function invoiceOrder($order){
    $invoice = $_invoiceService->prepareInvoice($order);
    $invoice->setRequestedCaptureCase(\Magento\Sales\Model\Order\Invoice::CAPTURE_ONLINE);
    $invoice->register();
    $transaction = $_transactionFactory->create()
        ->addObject($invoice)
        ->addObject($invoice->getOrder());
    $transaction->save();
    $order->setState('processing')->setStatus('processing');
    $order->save();
}

if(!$ame_transaction_id||$order->getState()=='new'){
    $valor_reembolsado = 0;
    $valor_total = 0;
}
else{
    $valor_total = $_dbAME->getTransactionAmount($ame_transaction_id);
    $valor_reembolsado = $_dbAME->getRefundedSumByTransactionId($ame_transaction_id);
}


?>
<style>
    form {
        display:inline;
    }
</style>
<script>
    function clickLoader(url){
        jQuery('body').loader('show');
        location.href = url;
    }
</script>
<?php
        if($order->getState()=='new'&&!$_dbAME->isCaptured($ame_transaction_id)) { ?>
    <button id="capturar" title="Capturar" type="button" class="action-default scalable ship primary"
            onclick="clickLoader('<?php echo $admin_url; ?>../ameroutes/capture/index/id/<?php echo $id; ?>/')"
            data-ui-id="sales-order-view-ship-button-sendorderame-button" >
        <span>Capturar</span>
    </button>
<?php }
        if($order->getState()=='new'&&!$_dbAME->isCaptured($ame_transaction_id)) { ?>
    <button id="cancelar" title="Cancelar" type="button" class="action-default scalable ship primary"
            onclick="clickLoader('<?php echo $admin_url; ?>../ameroutes/cancel/index/id/<?php echo $id; ?>/')"
            data-ui-id="sales-order-view-ship-button-sendorderame-button" >
        <span>Cancelar</span>
    </button>
<?php }
        if($order->getState()!='new') { ?>
    <form method="post" action="<?php echo $admin_url; ?>../ameroutes/refund/index/id/<?php echo $id; ?>">
    <button id="refund" title="Reembolsar" type="submit" class="action-default scalable ship primary"
            data-ui-id="sales-order-view-ship-button-sendorderame-button"
            onclick="jQuery('body').loader('show');">
        <span>Reembolsar</span>
    </button>
        <input name="form_key" type="hidden" value="<?php echo $formkey; ?>">
        <input type="text" name="valor" placeholder="valor em reais">
    </form>
<?php } ?>



<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Pedido AME - Capturar')); ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title">
                        <?= $block->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('ID Pedido AME')) ?></th>
                        <td><?= $block->escapeHtml($_dbAME->getAmeIdByIncrementId($increment_id)); ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('ID Transação AME')) ?></th>
                        <td><?= $block->escapeHtml($_dbAME->getTransactionIdByOrderId($_dbAME->getAmeIdByIncrementId($increment_id))); ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Valor do pedido')) ?></th>
                        <td><?= $block->escapeHtml(number_format($_dbAME->getOrderAmount($_dbAME->getAmeIdByIncrementId($increment_id))/100,2,",",".")); ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Valor recebido')) ?></th>
                        <td><?= $block->escapeHtml(number_format($valor_total/100,2,",",".")); ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Valor reembolsado')) ?></th>
                        <td><?= $block->escapeHtml(number_format($valor_reembolsado/100,2,",",".")); ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Valor disponível para reembolso')) ?></th>
                        <td><?= $block->escapeHtml(number_format(($valor_total-$valor_reembolsado)/100,2,",",".")); ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Captura - mensagem')) ?></th>
                        <td><?= $block->escapeHtml($mensagem); ?></td>
                    </tr>
                    <?= $block->getChildHtml() ?>
                </table>
            </div>
        </div>
    </div>
</section>


